[package]
edition = "2021"
name = "rustybrain-core"
version = "0.1.0"
[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
tree-sitter = "0.19.5"
tree-sitter-markdown = "0.7.1"
